baseurl : "/"
title : "Suparshva Developers Ltd."
url: "localhost:1313"  
author:
    name : "Atul Jain"
    site_name : "atulj.com"
    site_url : "http://atulj.com"
params:
    year: 2017
    company:
        name: "Suparshva Developers Ltd."
        phone : ["+91-9310036159", "+91-9999803268", "+91-9899615888"]
        email: "suparshvadevelopers@gmail.com"
        site: "www.suparshvadevelopers.com"
        address : "Z-7(SH), Loha Mandi, Naraina, New Delhi - 110028"
